// ═══════════════════════════════════════════════════════════════
//  SAMPLE DATA
// ═══════════════════════════════════════════════════════════════

import 'package:flutter/material.dart';
import 'package:learn_flutter/models/category_model.dart';
import 'package:learn_flutter/models/item_model.dart';

final List<CategoryModel> appCategories = [
  CategoryModel(
    id: 'electronics',
    name: 'Electronics',
    emoji: '📱',
    color: const Color(0xFF6C63FF),
    items: [
      ItemModel(
        id: 'e1',
        name: 'Wireless Earbuds',
        emoji: '🎧',
        price: 79.99,
        tag: 'mid-range',
        description: 'Noise-cancelling Bluetooth 5.3, 30h battery.',
      ),
      ItemModel(
        id: 'e2',
        name: 'Smart Watch',
        emoji: '⌚',
        price: 199.99,
        tag: 'premium',
        description: 'Heart rate, GPS, 7-day battery life.',
      ),
      ItemModel(
        id: 'e3',
        name: 'USB-C Hub',
        emoji: '🔌',
        price: 29.99,
        tag: 'budget',
        description: '7-in-1 hub: HDMI 4K, USB 3.0, SD card.',
      ),
      ItemModel(
        id: 'e4',
        name: 'Mechanical Keyboard',
        emoji: '⌨️',
        price: 89.99,
        tag: 'mid-range',
        description: 'TKL, RGB, tactile blue switches.',
      ),
    ],
  ),
  CategoryModel(
    id: 'books',
    name: 'Books',
    emoji: '📚',
    color: const Color(0xFFE91E8C),
    items: [
      ItemModel(
        id: 'b1',
        name: 'Clean Code',
        emoji: '📖',
        price: 35.99,
        tag: 'mid-range',
        description: 'Agile software craftsmanship by Robert C. Martin.',
      ),
      ItemModel(
        id: 'b2',
        name: 'Flutter in Action',
        emoji: '📘',
        price: 24.99,
        tag: 'budget',
        description: 'Build cross-platform apps with Flutter & Dart.',
      ),
      ItemModel(
        id: 'b3',
        name: 'Design Patterns',
        emoji: '📙',
        price: 45.00,
        tag: 'premium',
        description: 'The Gang of Four classic on OOP design.',
      ),
      ItemModel(
        id: 'b4',
        name: 'Atomic Habits',
        emoji: '📗',
        price: 14.99,
        tag: 'budget',
        description: 'Proven ways to build good habits.',
      ),
    ],
  ),
  CategoryModel(
    id: 'fashion',
    name: 'Fashion',
    emoji: '👗',
    color: const Color(0xFFFFA726),
    items: [
      ItemModel(
        id: 'f1',
        name: 'Denim Jacket',
        emoji: '🧥',
        price: 59.99,
        tag: 'mid-range',
        description: 'Classic blue denim — timeless for any season.',
      ),
      ItemModel(
        id: 'f2',
        name: 'Sneakers',
        emoji: '👟',
        price: 89.99,
        tag: 'mid-range',
        description: 'Lightweight with memory foam insole.',
      ),
      ItemModel(
        id: 'f3',
        name: 'Cap',
        emoji: '🧢',
        price: 19.99,
        tag: 'budget',
        description: 'Embroidered cotton cap, adjustable strap.',
      ),
    ],
  ),
  CategoryModel(
    id: 'sports',
    name: 'Sports',
    emoji: '⚽',
    color: const Color(0xFF43A047),
    items: [
      ItemModel(
        id: 's1',
        name: 'Yoga Mat',
        emoji: '🧘',
        price: 34.99,
        tag: 'mid-range',
        description: 'Extra-thick 6mm non-slip with carrying strap.',
      ),
      ItemModel(
        id: 's2',
        name: 'Resistance Bands',
        emoji: '💪',
        price: 18.99,
        tag: 'budget',
        description: 'Set of 5 latex bands (10–50 lb).',
      ),
      ItemModel(
        id: 's3',
        name: 'Basketball',
        emoji: '🏀',
        price: 49.99,
        tag: 'mid-range',
        description: 'Official size 7, indoor/outdoor composite.',
      ),
    ],
  ),
  CategoryModel(
    id: 'food',
    name: 'Food',
    emoji: '🍕',
    color: const Color(0xFFEF5350),
    items: [
      ItemModel(
        id: 'fo1',
        name: 'Protein Bars',
        emoji: '🍫',
        price: 22.99,
        tag: 'mid-range',
        description: 'Box of 12 mixed-flavor bars, 20g protein each.',
      ),
      ItemModel(
        id: 'fo2',
        name: 'Coffee Beans',
        emoji: '☕',
        price: 16.99,
        tag: 'budget',
        description: 'Ethiopian Yirgacheffe, 500g whole bean.',
      ),
      ItemModel(
        id: 'fo3',
        name: 'Meal Kit',
        emoji: '🥗',
        price: 79.99,
        tag: 'premium',
        description: 'Weekly 3-meal kit with fresh ingredients.',
      ),
    ],
  ),
  CategoryModel(
    id: 'travel',
    name: 'Travel',
    emoji: '✈️',
    color: const Color(0xFF00ACC1),
    items: [
      ItemModel(
        id: 't1',
        name: 'Passport Holder',
        emoji: '📔',
        price: 24.99,
        tag: 'budget',
        description: 'RFID-blocking genuine leather wallet.',
      ),
      ItemModel(
        id: 't2',
        name: 'Neck Pillow',
        emoji: '😴',
        price: 29.99,
        tag: 'mid-range',
        description: 'Memory foam U-pillow, washable cover.',
      ),
      ItemModel(
        id: 't3',
        name: 'Luggage Scale',
        emoji: '⚖️',
        price: 12.99,
        tag: 'budget',
        description: 'Digital handheld scale up to 50 kg.',
      ),
      ItemModel(
        id: 't4',
        name: 'Travel Backpack',
        emoji: '🎒',
        price: 119.99,
        tag: 'premium',
        description: '40L carry-on with laptop sleeve.',
      ),
    ],
  ),
];
